version: "3.8"

services:
  client:
    build:
      context: ./client
    ports:
      - "5174:80"
    restart: unless-stopped
    networks:
      - demo-net

networks:
  demo-net:
    external: true
