services:
  client: #nombre del servicio
    build: 
      context: ./client
    ports:
       - "5173:80"
    restart: unless-stopped
    networks:
      - demo-net

networks:
  demo-net:
    external: true