services:
  client:
    build:
      context: ./client
    ports:
      - "5174:80"  # cambia si el puerto está ocupado
    restart: unless-stopped
    networks:
      - demo-net

networks:
  demo-net:
    external: true
